// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOABCziBAJYpHTH4hm7S315eUbIm3KU0',
    appId: '1:90098497634:web:5dee9f5cf741df7cb0793b',
    messagingSenderId: '90098497634',
    projectId: 'chinese-app-cfe75',
    authDomain: 'chinese-app-cfe75.firebaseapp.com',
    storageBucket: 'chinese-app-cfe75.firebasestorage.app',
    measurementId: 'G-QDGK401GFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBll_Xz6HTlyVf9q-y3BZZuwR1fUHuHsoI',
    appId: '1:90098497634:android:806ec9b7dd472d21b0793b',
    messagingSenderId: '90098497634',
    projectId: 'chinese-app-cfe75',
    storageBucket: 'chinese-app-cfe75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPwiA1aumgrqDI_7aXnABXwuHfurrUazs',
    appId: '1:90098497634:ios:402f2b3e79a9b43db0793b',
    messagingSenderId: '90098497634',
    projectId: 'chinese-app-cfe75',
    storageBucket: 'chinese-app-cfe75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPwiA1aumgrqDI_7aXnABXwuHfurrUazs',
    appId: '1:90098497634:ios:402f2b3e79a9b43db0793b',
    messagingSenderId: '90098497634',
    projectId: 'chinese-app-cfe75',
    storageBucket: 'chinese-app-cfe75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOABCziBAJYpHTH4hm7S315eUbIm3KU0',
    appId: '1:90098497634:web:94dea3d0c1a80698b0793b',
    messagingSenderId: '90098497634',
    projectId: 'chinese-app-cfe75',
    authDomain: 'chinese-app-cfe75.firebaseapp.com',
    storageBucket: 'chinese-app-cfe75.firebasestorage.app',
    measurementId: 'G-0YV4D7R397',
  );
}
